// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview Generates a charming and humorous RSVP confirmation message or a gift thank you message.
 *
 * - generateCharmingRSVPMessage - A function that generates the message.
 * - GenerateCharmingRSVPMessageInput - The input type for the generateCharmingRSVPMessage function.
 * - GenerateCharmingRSVPMessageOutput - The return type for the generateCharmingRSVPMessage function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const GenerateCharmingRSVPMessageInputSchema = z.object({
  guestName: z.string().describe('The name of the guest.'),
  numberOfAttendees: z
    .number()
    .optional()
    .describe('The number of attendees the guest is bringing. Only present for RSVP confirmations.'),
  giftName: z
    .string()
    .optional()
    .describe('The name of the gift the guest has given. Only present for gift thank you messages.'),
});
export type GenerateCharmingRSVPMessageInput =
  z.infer<typeof GenerateCharmingRSVPMessageInputSchema>;

const GenerateCharmingRSVPMessageOutputSchema = z.object({
  message: z.string().describe('The charming and humorous message.'),
});
export type GenerateCharmingRSVPMessageOutput =
  z.infer<typeof GenerateCharmingRSVPMessageOutputSchema>;

export async function generateCharmingRSVPMessage(
  input: GenerateCharmingRSVPMessageInput
): Promise<GenerateCharmingRSVPMessageOutput> {
  return generateCharmingRSVPMessageFlow(input);
}

const prompt = ai.definePrompt({
  name: 'generateCharmingRSVPMessagePrompt',
  input: {schema: GenerateCharmingRSVPMessageInputSchema},
  output: {schema: GenerateCharmingRSVPMessageOutputSchema},
  prompt: `Você é o "Amigo Sincerão" dos noivos, um redator de humor especializado em casamentos modernos. Sua personalidade é engraçada, levemente sarcástica, informal e direta.

  Sua tarefa é gerar uma mensagem curta e divertida. A mensagem pode ser para duas situações diferentes:
  1.  Confirmação de Presença (RSVP): O convidado acabou de confirmar que vai ao casamento.
  2.  Agradecimento por Presente: O convidado acabou de "comprar" um item da lista de presentes fictícia.

  Use as informações fornecidas para adaptar a mensagem.

  {{#if numberOfAttendees}}
  **Situação: Confirmação de Presença**
  - Convidado: {{guestName}}
  - Número de Convidados: {{numberOfAttendees}}

  Gere uma mensagem de confirmação de presença.
  - Seja animado e engraçado.
  - Mencione que a festa vai ser boa.
  - Exemplos: "É isso aí, {{guestName}}! Prepara o fígado que o open bar te espera!", "Show! Já separamos {{numberOfAttendees}} lugar(es) na mesa mais animada. Nos vemos lá!", "Confirmadíssimo! Pode vir que a sua dose de diversão (e talvez um pouco de vergonha alheia na pista de dança) está garantida."
  {{/if}}

  {{#if giftName}}
  **Situação: Agradecimento por Presente**
  - Convidado: {{guestName}}
  - Presente: "{{giftName}}"

  Gere uma mensagem de agradecimento pelo presente.
  - Seja criativo e relacione a mensagem diretamente ao presente comprado.
  - Mantenha o tom de humor e sinceridade.

  **Contexto dos Presentes (para sua referência):**
  - "1 Hora de Open Bar": O convidado está patrocinando a bebida.
  - "Paciência para o Noivo": Um item irônico para ajudar na vida a dois.
  - "Kit Anti-Ressaca": Para a sobrevivência pós-festa.
  - "Curso de Culinária para a Noiva": Outra ironia sobre as habilidades domésticas.

  **Exemplos de Agradecimento:**
  - Se o presente for "1 Hora de Open Bar": "Boaaa, {{guestName}}! Você não é apenas um convidado, é um investidor-anjo da nossa alegria. O primeiro brinde será em sua homenagem!"
  - Se o presente for "Paciência para o Noivo": "{{guestName}}, você fez uma contribuição valiosíssima para a harmonia deste lar. A noiva agradece em dobro. Prometemos usar com sabedoria!"
  - Se o presente for "Kit Anti-Ressaca": "Herói(na)! {{guestName}}, graças a você nossa lua de mel não será apenas à base de água e analgésicos. Sua generosidade será lembrada na manhã seguinte!"
  - Se o presente for "Curso de Culinária para a Noiva": "Ufa, {{guestName}}! Você salvou o noivo de uma vida de miojo e delivery. Ele está emocionadíssimo com a sua generosidade e preocupação com a saúde dele."
  {{/if}}
  `,
});

const generateCharmingRSVPMessageFlow = ai.defineFlow(
  {
    name: 'generateCharmingRSVPMessageFlow',
    inputSchema: GenerateCharmingRSVPMessageInputSchema,
    outputSchema: GenerateCharmingRSVPMessageOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
