// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview Generates a witty and understanding message for a guest who declines an RSVP.
 *
 * - generateWittyDeclineMessage - A function that generates the message.
 * - GenerateWittyDeclineMessageInput - The input type for the function.
 * - GenerateWittyDeclineMessageOutput - The return type for the function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const GenerateWittyDeclineMessageInputSchema = z.object({
  guestName: z.string().describe('The name of the guest who is declining.'),
});
export type GenerateWittyDeclineMessageInput =
  z.infer<typeof GenerateWittyDeclineMessageInputSchema>;

const GenerateWittyDeclineMessageOutputSchema = z.object({
  message: z.string().describe('The witty and understanding decline message.'),
});
export type GenerateWittyDeclineMessageOutput =
  z.infer<typeof GenerateWittyDeclineMessageOutputSchema>;

export async function generateWittyDeclineMessage(
  input: GenerateWittyDeclineMessageInput
): Promise<GenerateWittyDeclineMessageOutput> {
  return generateWittyDeclineMessageFlow(input);
}

const prompt = ai.definePrompt({
  name: 'generateWittyDeclineMessagePrompt',
  input: {schema: GenerateWittyDeclineMessageInputSchema},
  output: {schema: GenerateWittyDeclineMessageOutputSchema},
  prompt: `Você é o "Amigo Sincerão" dos noivos, um redator de humor especializado em casamentos modernos. Sua personalidade é engraçada, levemente sarcástica, informal e direta.

  Um convidado chamado {{guestName}} acabou de recusar o convite para o casamento (clicou em "Vou dar o cano").

  Gere uma mensagem curta, espirituosa e compreensiva que confirme a recusa. A mensagem deve fazer com que a pessoa se sinta lembrada, mas sem culpa. Deve ser leve e amigável. Mantenha o idioma em Português do Brasil.

  Exemplos de Tom:
  - "Poxa, {{guestName}}! A pista de dança sentirá sua falta, mas a gente se encontra pra comemorar depois. Sem ressentimentos!"
  - "Que pena que você não vem, {{guestName}}! Vamos beber um drink em sua homenagem (ou vários). Sentiremos sua falta!"
  - "Recebido, {{guestName}}. A festa não será a mesma sem suas danças constrangedoras, mas a gente supera. Brincadeira! Tudo de bom e nos vemos em breve!"
  `,
});

const generateWittyDeclineMessageFlow = ai.defineFlow(
  {
    name: 'generateWittyDeclineMessageFlow',
    inputSchema: GenerateWittyDeclineMessageInputSchema,
    outputSchema: GenerateWittyDeclineMessageOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
