// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview Generates a funny product description and thank you note for a wedding gift.
 *
 * - generateGiftText - A function that generates the texts.
 * - GenerateGiftTextInput - The input type for the function.
 * - GenerateGiftTextOutput - The return type for the function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const GenerateGiftTextInputSchema = z.object({
  giftTitle: z.string().describe('The title of the wedding gift.'),
});
export type GenerateGiftTextInput = z.infer<typeof GenerateGiftTextInputSchema>;

const GenerateGiftTextOutputSchema = z.object({
  description: z.string().describe('A short, funny, and creative product description for the gift list.'),
  thankYouNote: z.string().describe('A short, witty, and personal thank you note to be shown after the guest "buys" the gift.'),
});
export type GenerateGiftTextOutput = z.infer<typeof GenerateGiftTextOutputSchema>;

export async function generateGiftText(
  input: GenerateGiftTextInput
): Promise<GenerateGiftTextOutput> {
  return generateGiftTextFlow(input);
}

const prompt = ai.definePrompt({
  name: 'generateGiftTextPrompt',
  input: {schema: GenerateGiftTextInputSchema},
  prompt: `Você é o "Amigo Sincerão" dos noivos, um redator de humor especialista em casamentos. Sua personalidade é engraçada, levemente sarcástica, informal e direta.

  Sua tarefa é criar dois textos para um item da lista de presentes fictícia de um casamento, baseado no título do presente fornecido.

  Título do Presente: "{{giftTitle}}"

  1.  **Descrição do Produto (para a lista):** Crie uma descrição curta (1-2 frases), divertida e criativa que explique o "produto" de forma humorística. O objetivo é fazer o convidado rir e querer "comprar" o presente (que é uma doação em PIX).
      - Exemplo para "1 Hora de Open Bar": "Garanta a alegria dos noivos (e a sua) com mais uma hora de bons drinks. Um investimento com retorno garantido na pista de dança."
      - Exemplo para "Jantar Romântico a Luz de Velas (sem queimar a casa)": "Patrocine nosso primeiro jantar chique como casados. Prometemos não usar o extintor de incêndio como peça de decoração."

  2.  **Mensagem de Agradecimento (pós-compra):** Crie uma mensagem curta de agradecimento que será exibida logo após o convidado fazer a doação. Deve ser espirituosa e diretamente relacionada ao presente.
      - Exemplo para "1 Hora de Open Bar": "Boaaa! Você não é apenas um convidado, é um investidor-anjo da nossa felicidade etílica. O primeiro brinde será em sua homenagem!"
      - Exemplo para "Jantar Romântico a Luz de Velas": "Obrigado! Graças a você, nosso primeiro jantar não será pão com ovo. Você acaba de salvar nosso casamento do tédio gastronômico."

  Responda com um objeto JSON com as chaves "description" e "thankYouNote".
  Gere a descrição e a mensagem de agradecimento para o presente "{{giftTitle}}".
  `,
});

const generateGiftTextFlow = ai.defineFlow(
  {
    name: 'generateGiftTextFlow',
    inputSchema: GenerateGiftTextInputSchema,
    outputSchema: GenerateGiftTextOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    const response = output as GenerateGiftTextOutput;
    return response;
  }
);
