// This is an autogenerated file from Firebase Studio.
/**
 * Converte uma string de cor (hex, rgb, nome) para um objeto HSL.
 * Retorna null se a cor for inválida.
 */
export function colorToHsl(colorStr: string | undefined): { h: number; s: number; l: number } | null {
  if (typeof window === 'undefined' || !colorStr) return null;

  // Usa um elemento temporário para obter o valor RGB computado, lidando com nomes de cores
  const tempEl = document.createElement('div');
  tempEl.style.color = colorStr;
  document.body.appendChild(tempEl);

  const computedColor = window.getComputedStyle(tempEl).color;
  document.body.removeChild(tempEl);

  const rgbMatch = computedColor.match(/rgb\((\d+),\s*(\d+),\s*(\d+)\)/);
  if (!rgbMatch) return null;

  let r = parseInt(rgbMatch[1], 10) / 255;
  let g = parseInt(rgbMatch[2], 10) / 255;
  let b = parseInt(rgbMatch[3], 10) / 255;

  const max = Math.max(r, g, b);
  const min = Math.min(r, g, b);
  let h = 0, s, l = (max + min) / 2;

  if (max === min) {
    h = s = 0; // achromatic
  } else {
    const d = max - min;
    s = l > 0.5 ? d / (2 - max - min) : d / (max + min);
    switch (max) {
      case r: h = (g - b) / d + (g < b ? 6 : 0); break;
      case g: h = (b - r) / d + 2; break;
      case b: h = (r - g) / d + 4; break;
    }
    h /= 6;
  }

  return {
    h: Math.round(h * 360),
    s: Math.round(s * 100),
    l: Math.round(l * 100)
  };
}


/**
 * Calcula o YIQ para determinar se uma cor de fundo precisa de texto claro ou escuro.
 */
export function getYiq(color: {r: number, g: number, b: number}): number {
    return ((color.r * 299) + (color.g * 587) + (color.b * 114)) / 1000;
}

export function hexToRgb(hex: string): {r: number, g: number, b: number} | null {
    if (!hex) return null;
    const result = /^#?([a-f\d]{2})([a-f\d]{2})([a-f\d]{2})$/i.exec(hex);
    return result ? {
        r: parseInt(result[1], 16),
        g: parseInt(result[2], 16),
        b: parseInt(result[3], 16)
    } : null;
}

export function colorStringToHex(colorStr: string | undefined): string | null {
    if (typeof window === 'undefined' || !colorStr) return null;
    
    // If it's already a valid hex, return it
    if (/^#[0-9a-f]{3,6}$/i.test(colorStr)) {
        return colorStr;
    }

    const tempEl = document.createElement('div');
    tempEl.style.color = colorStr;
    document.body.appendChild(tempEl);
    const computedColor = window.getComputedStyle(tempEl).color;
    document.body.removeChild(tempEl);

    const rgbMatch = computedColor.match(/rgb\((\d+),\s*(\d+),\s*(\d+)\)/);
    if (!rgbMatch) return null;

    const r = parseInt(rgbMatch[1], 10);
    const g = parseInt(rgbMatch[2], 10);
    const b = parseInt(rgbMatch[3], 10);

    const toHex = (c: number) => ('0' + c.toString(16)).slice(-2);

    return `#${toHex(r)}${toHex(g)}${toHex(b)}`;
}
