// This is an autogenerated file from Firebase Studio.
export const colorPalette = [
    // Tons neutros
    { name: 'Branco', hex: '#FFFFFF' },
    { name: 'Branco Neve', hex: '#FFFAFA' },
    { name: 'Cinza Claro', hex: '#D3D3D3' },
    { name: 'Prata', hex: '#C0C0C0' },
    { name: 'Cinza', hex: '#808080' },
    { name: 'Grafite', hex: '#36454F' },
    { name: 'Preto', hex: '#000000' },
    { name: 'Marfim', hex: '#FFFFF0' },
    { name: 'Bege', hex: '#F5F5DC' },

    // Tons de Vermelho e Rosa
    { name: 'Vermelho', hex: '#FF0000' },
    { name: 'Marsala', hex: '#B57170' },
    { name: 'Bordô', hex: '#800000' },
    { name: 'Terracota', hex: '#E2725B' },
    { name: 'Coral', hex: '#FF7F50' },
    { name: 'Rosa Claro', hex: '#FFB6C1' },
    { name: 'Rosa Chá', hex: '#D8BFD8' },
    { name: 'Rosa Antigo', hex: '#C08081' },
    { name: 'Rosa Millennial', hex: '#FADADD' },
    { name: 'Fúcsia', hex: '#FF00FF' },
    { name: 'Magenta', hex: '#FF00FF' },
    { name: 'Framboesa', hex: '#E30B5D'},

    // Tons de Laranja e Amarelo
    { name: 'Laranja', hex: '#FFA500' },
    { name: 'Laranja Queimado', hex: '#CC5500' },
    { name: 'Pêssego', hex: '#FFE5B4' },
    { name: 'Dourado', hex: '#FFD700' },
    { name: 'Amarelo', hex: '#FFFF00' },
    { name: 'Mostarda', hex: '#FFDB58' },

    // Tons de Verde
    { name: 'Verde Limão', hex: '#32CD32' },
    { name: 'Verde', hex: '#008000' },
    { name: 'Verde Oliva', hex: '#808000' },
    { name: 'Verde Musgo', hex: '#ADDFAD' },
    { name: 'Verde Sálvia', hex: '#8FBC8F' },
    { name: 'Verde Menta', hex: '#98FF98' },
    { name: 'Verde Esmeralda', hex: '#50C878' },
    { name: 'Verde Água', hex: '#00FFFF' },
    { name: 'Verde Tiffany', hex: '#0ABAB5' },

    // Tons de Azul
    { name: 'Ciano', hex: '#00FFFF' },
    { name: 'Azul Celeste', hex: '#87CEEB' },
    { name: 'Azul Turquesa', hex: '#40E0D0' },
    { name: 'Azul Tiffany', hex: '#0ABAB5' },
    { name: 'Azul', hex: '#0000FF' },
    { name: 'Azul Royal', hex: '#4169E1' },
    { name: 'Azul Marinho', hex: '#000080' },
    { name: 'Azul Petróleo', hex: '#008080' },
    { name: 'Azul Serenity', hex: '#92A8D1' },

    // Tons de Roxo e Lilás
    { name: 'Roxo', hex: '#800080' },
    { name: 'Lavanda', hex: '#E6E6FA' },
    { name: 'Lilás', hex: '#C8A2C8' },
    { name: 'Violeta', hex: '#8F00FF' },
    { name: 'Ametista', hex: '#9966CC' },
    { name: 'Orquídea', hex: '#DA70D6'},

    // Tons de Marrom
    { name: 'Marrom', hex: '#A52A2A' },
    { name: 'Chocolate', hex: '#D2691E' },
    { name: 'Caramelo', hex: '#AF6E4D' },
];
