// This is an autogenerated file from Firebase Studio.
'use client';

import { type User, onIdTokenChanged } from 'firebase/auth';
import { useEffect, useState } from 'react';

import { useAuth } from '../provider';

export type FirebaseUser = User | null;

export function useUser() {
  const auth = useAuth();
  const [user, setUser] = useState<FirebaseUser>(auth?.currentUser ?? null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    if (!auth) {
      setLoading(false);
      return;
    }

    const unsubscribe = onIdTokenChanged(auth, (firebaseUser: FirebaseUser) => {
      setUser(firebaseUser);
      setLoading(false);
    });

    return () => unsubscribe();
  }, [auth]);

  return { user, loading };
}
