// This is an autogenerated file from Firebase Studio.
'use client';

import { useEffect, useState } from 'react';
import {
  collection,
  onSnapshot,
  type Query,
  queryEqual,
  where,
  getDocsFromServer,
  type QuerySnapshot,
} from 'firebase/firestore';

import { useFirestore } from '../provider';
import { DocumentData } from '../types';
import { errorEmitter } from '../error-emitter';
import { FirestorePermissionError } from '../errors';

type CollectionOptions<T> = {
  where?: [string, '==', string];
  initialData?: T[];
};

export function useCollection<T = DocumentData>(
  path: string,
  options?: CollectionOptions<T>
) {
  const firestore = useFirestore();

  const [data, setData] = useState<T[] | null>(options?.initialData ?? null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<Error | null>(null);

  useEffect(() => {
    if (!firestore) {
      return;
    }

    let q: Query;
    const ref = collection(firestore, path);

    if (options?.where) {
      q = where(ref, options.where[0], options.where[1], options.where[2]);
    } else {
      q = ref;
    }

    const unsubscribe = onSnapshot(
      q,
      (snapshot) => {
        const data: T[] = [];
        snapshot.forEach((doc) => {
          data.push({ ...doc.data(), id: doc.id } as T);
        });

        setData(data);
        setLoading(false);
      },
      (err) => {
        const permissionError = new FirestorePermissionError({
          path: ref.path,
          operation: 'list',
        });
        errorEmitter.emit('permission-error', permissionError);
        setError(permissionError);
        setLoading(false);
      }
    );

    return () => unsubscribe();
  }, [firestore, path, options?.where]);

  return { data, loading, error };
}
