// This is an autogenerated file from Firebase Studio.
// It is not meant to be edited.
import { initializeApp, getApps, getApp, App } from 'firebase-admin/app';
import { getFirestore, Firestore } from 'firebase-admin/firestore';
import { getAuth, Auth } from 'firebase-admin/auth';

interface FirebaseAdmin {
  app: App;
  firestore: Firestore;
  auth: Auth;
}

let admin: FirebaseAdmin | null = null;

function getFirebaseAdmin(): FirebaseAdmin {
  if (admin) {
    return admin;
  }

  const app = !getApps().length
    ? initializeApp({
        projectId: 'meu-casamento-d28e1',
        storageBucket: 'meu-casamento-d28e1.appspot.com',
        serviceAccountId: 'firebase-adminsdk-fbsvc@meu-casamento-d28e1.iam.gserviceaccount.com'
      })
    : getApp();

  const firestore = getFirestore(app);
  const auth = getAuth(app);

  admin = { app, firestore, auth };

  return admin;
}

export { getFirebaseAdmin };
