// This is an autogenerated file from Firebase Studio.
// It is not meant to be edited.
import { initializeApp, getApps, getApp, App } from 'firebase-admin/app';
import { getFirestore, Firestore } from 'firebase-admin/firestore';
import { getAuth, Auth } from 'firebase-admin/auth';
import { firebaseConfig } from './config';

interface FirebaseAdmin {
  app: App;
  firestore: Firestore;
  auth: Auth;
}

let admin: FirebaseAdmin | null = null;

function getFirebaseAdmin(): FirebaseAdmin {
  if (admin) {
    return admin;
  }

  const app = !getApps().length
    ? initializeApp({
        // When deployed to App Hosting, these are automatically set.
        // For local development, you need to set these environment variables.
        // See: https://firebase.google.com/docs/admin/setup#initialize-sdk
      })
    : getApp();

  const firestore = getFirestore(app);
  const auth = getAuth(app);

  admin = { app, firestore, auth };

  return admin;
}

export { getFirebaseAdmin };
