// This is an autogenerated file from Firebase Studio.
'use client';

import { ReactNode } from 'react';

import { useFirebaseServices } from './use-firebase-services';
import { FirebaseProvider } from './provider';

interface FirebaseClientProviderProps {
  children: ReactNode;
}

export function FirebaseClientProvider({
  children,
}: FirebaseClientProviderProps) {
  const services = useFirebaseServices();

  return (
    <FirebaseProvider {...services}>
      {children}
    </FirebaseProvider>
  );
}
