// This is an autogenerated file from Firebase Studio.
'use client';

import { ReactNode } from 'react';

import { useFirebaseServices } from './use-firebase-services';
import { FirebaseProvider } from './provider';

interface FirebaseClientProviderProps {
  children: ReactNode;
}

export function FirebaseClientProvider({
  children,
}: FirebaseClientProviderProps) {
  const { app, auth, firestore } = useFirebaseServices();

  return (
    <FirebaseProvider app={app} auth={auth} firestore={firestore}>
      {children}
    </FirebaseProvider>
  );
}
