// This is an autogenerated file from Firebase Studio.
// It is not meant to be edited.
import { initializeApp, getApps, getApp } from 'firebase/app';
import { getAnalytics } from "firebase/analytics";
import { config } from 'dotenv';

config(); // Load environment variables from .env file

// Your web app's Firebase configuration
// For Firebase JS SDK v7.20.0 and later, measurementId is optional
const firebaseConfig = {
  apiKey: process.env.NEXT_PUBLIC_FIREBASE_API_KEY,
  authDomain: process.env.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN,
  projectId: process.env.NEXT_PUBLIC_FIREBASE_PROJECT_ID,
  storageBucket: process.env.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET,
  messagingSenderId: process.env.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID,
  appId: process.env.NEXT_PUBLIC_FIREBASE_APP_ID,
  measurementId: process.env.NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID,
};


function initializeFirebase() {
  const app = !getApps().length ? initializeApp(firebaseConfig) : getApp();
  // We only want to track analytics in the browser
  if (typeof window !== 'undefined') {
    // Check if the measurement ID is available
    if (firebaseConfig.measurementId) {
      getAnalytics(app);
    }
  }
  return app;
}

export { initializeFirebase, firebaseConfig };
