// This is an autogenerated file from Firebase Studio.
// It is not meant to be edited.
import { initializeApp, getApps, getApp } from 'firebase/app';
import { getAnalytics } from "firebase/analytics";

// Your web app's Firebase configuration
// For Firebase JS SDK v7.20.0 and later, measurementId is optional
const firebaseConfig = {
  apiKey: "AIzaSyA3FoCZLOzzZCCxM7GTxLERd2h2zSk1kYM",
  authDomain: "meu-casamento-d28e1.firebaseapp.com",
  projectId: "meu-casamento-d28e1",
  storageBucket: "meu-casamento-d28e1.appspot.com",
  messagingSenderId: "212546661288",
  appId: "1:212546661288:web:b9cd0b115cdbf3c33c0b9d",
  measurementId: "G-W6VCNKM86G",
};


function initializeFirebase() {
  const app = !getApps().length ? initializeApp(firebaseConfig) : getApp();
  // We only want to track analytics in the browser
  if (typeof window !== 'undefined') {
    // Check if the measurement ID is available
    if (firebaseConfig.measurementId) {
      getAnalytics(app);
    }
  }
  return app;
}

export { initializeFirebase, firebaseConfig };
