// This is an autogenerated file from Firebase Studio.
import { EventEmitter } from 'events';
import { type FirestorePermissionError } from './errors';

type Events = {
  'permission-error': (error: FirestorePermissionError) => void;
};

// @ts-expect-error - we are not using all of the EventEmitter methods.
class TypedEventEmitter extends EventEmitter {
  emit<T extends keyof Events>(event: T, ...args: Parameters<Events[T]>): boolean {
    return super.emit(event, ...args);
  }

  on<T extends keyof Events>(event: T, listener: Events[T]): this {
    return super.on(event, listener);
  }
}

export const errorEmitter = new TypedEventEmitter() as TypedEventEmitter;
