// This is an autogenerated file from Firebase Studio.
export type SecurityRuleContext = {
  path: string;
  operation: 'get' | 'list' | 'create' | 'update' | 'delete';
  requestResourceData?: any;
};

export class FirestorePermissionError extends Error {
  public readonly context: SecurityRuleContext;
  constructor(context: SecurityRuleContext) {
    super(`FirestoreError: Missing or insufficient permissions: The following request was denied by Firestore Security Rules:\n${JSON.stringify(context, null, 2)}`);
    this.name = 'FirestorePermissionError';
    this.context = context;
    
    // This is to make the error message more readable in the Next.js error overlay
    this.stack = '';
  }
}
