// This is an autogenerated file from Firebase Studio.
'use client';

import { useState, useEffect } from 'react';
import { initializeApp, getApp, getApps, type FirebaseApp } from 'firebase/app';
import { getAuth, type Auth } from 'firebase/auth';
import { getFirestore, type Firestore } from 'firebase/firestore';
import { firebaseConfig } from './config';

interface FirebaseServices {
  app: FirebaseApp | null;
  auth: Auth | null;
  firestore: Firestore | null;
}

export function useFirebaseServices(): FirebaseServices {
  const [services, setServices] = useState<FirebaseServices>({
    app: null,
    auth: null,
    firestore: null,
  });

  useEffect(() => {
    const app =
      getApps().length === 0 ? initializeApp(firebaseConfig) : getApp();
    const auth = getAuth(app);
    const firestore = getFirestore(app);

    setServices({ app, auth, firestore });
  }, []);

  return services;
}
