// This is an autogenerated file from Firebase Studio.
'use client';

import { useState, useEffect } from 'react';
import { initializeApp, getApp, getApps, type FirebaseApp } from 'firebase/app';
import { getAuth, type Auth } from 'firebase/auth';
import { getFirestore, type Firestore } from 'firebase/firestore';
import { firebaseConfig } from './config';

interface FirebaseServices {
  app: FirebaseApp | null;
  auth: Auth | null;
  firestore: Firestore | null;
}

// Create a single instance of services to be shared across the app
let firebaseServices: FirebaseServices | null = null;

function initializeFirebaseServices(): FirebaseServices {
  if (firebaseServices) {
    return firebaseServices;
  }
  
  if (firebaseConfig && firebaseConfig.apiKey) {
    const app = getApps().length === 0 ? initializeApp(firebaseConfig) : getApp();
    const auth = getAuth(app);
    const firestore = getFirestore(app);

    firebaseServices = { app, auth, firestore };
    return firebaseServices;
  }
  
  return { app: null, auth: null, firestore: null };
}


export function useFirebaseServices(): FirebaseServices {
  // Use state to make the component re-render once services are available.
  const [services, setServices] = useState<FirebaseServices>(initializeFirebaseServices());

  // Although we initialize sync, we can use an effect to be safe, 
  // especially if the config were to load async in the future.
  useEffect(() => {
    if (!services.app) {
        setServices(initializeFirebaseServices());
    }
  }, [services.app]);


  return services;
}
