// This is an autogenerated file from Firebase Studio.
'use client';

import { useEffect } from 'react';
import { errorEmitter } from '@/firebase/error-emitter';

export function FirebaseErrorListener() {
  useEffect(() => {
    const unsubscribe = errorEmitter.on('permission-error', (error) => {
      // We are throwing this error to make it visible in the Next.js error overlay
      // during development. This helps with debugging security rules.
      throw error;
    });
    return () => {
      // @ts-expect-error - we are not using all of the EventEmitter methods.
      unsubscribe();
    };
  }, []);

  return null;
}
